name: foda_admin
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #firebase Auth
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  # firebase_admin: ^1.11.0


  #firebase database
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.8.2

  #state management control
  provider: ^6.0.5
  either_dart: ^0.4.0
  get_it: ^7.6.0

  #utils
  intl: ^0.18.1
  equatable: ^2.0.5
  random_string: ^2.3.1
  file_picker: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: ArimaMadurai
      fonts:
        - asset: assets/fonts/ArimaMadurai-Regular.ttf
          weight: 400
        - asset: assets/fonts/ArimaMadurai-Medium.ttf
          weight: 500
        - asset: assets/fonts/ArimaMadurai-Bold.ttf
          weight: 700
